version: '1.0' # versão desse documento  
squad:
  slug: 'viaops' # id da squad responsável por esse projeto
service-now:
  sys-id: 70f42ec1dbcc449830404410ba9619c2
jira:
  key: 'DXT' # key do projeto no jira (project_key na url)
depends-on: #  (opcional)
  - produto_3 # nome do produto utilizado por esse projeto
component-of: # (opcional)
  - name: viaops # nome do produto ao qual esse projeto pertence
deploy: # (opcional)
  namespace-prefix: 'adlm-dummy' # prefixo do namespace desse projeto para ser usado na etapa de CD
